# Generated by Django 6.0.8 on 2026-09-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkrecord',
            name='synced_to_render',
            field=models.BooleanField(default=False, verbose_name='已轉發至 Render'),
        ),
    ]
